/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
      // 'introduction',
      {
        type: 'category',
        label: 'Fine-Tuning',
        items: [
            'quickstart',
            'fine-tuning/datasets',
            'fine-tuning/parameters',
            'fine-tuning/testing',
            'fine-tuning/deployment',
        ],
      },
      {
        type: 'category',
        label: 'Guides',
        items: [
            'guides/data-extraction',
            'guides/classification',
            'guides/embeddings',
            'guides/emissary-classification',
        ]
      }
  ],
  tutorialSidebar: [
    { type: "doc", id: "intro"},
    { type: "autogenerated", dirName: "tutorial-basics" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/emissary-api"
      },
      items: require("./docs/emissary-api/sidebar.ts")
    }
  ]
};

export default sidebars;